name: build push and deploy image

on:
#   workflow_dispatch:

  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
      id-token: write
      contents: read

env:
  AWS_REGION: us-east-1
  AWS_ROLE: ${{secrets.AWS_ACTIONS_ROLE}}
  AWS_ACCESS: ${{secrets.AWS_ACCESS}}
  AWS_SECRET: ${{secrets.AWS_SECRET}}

jobs:

  build:
    runs-on: ubuntu-latest # github-runner
    
    steps:
      - name: checkout - clone repo
        uses: actions/checkout@v3

      - name: AWS creds configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ env.AWS_REGION }}
      - name: login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: ecr-login