name: build push and deploy image

on:
#   workflow_dispatch:

  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
      id-token: write
      contents: read

env:
  AWS_REGION: us-east-1
  AWS_ROLE: ${{secrets.AWS_ACTIONS_ROLE}}
  AWS_ACCESS: ${{secrets.AWS_ACCESS}}
  AWS_SECRET: ${{secrets.AWS_SECRET}}
  ECR_REPO_NAME: dev
  IMAGE_TAG: ${{github.run_number}}

jobs:

  build:
    runs-on: ubuntu-latest # github-runner
    
    steps:
      - name: checkout - clone repo
        uses: actions/checkout@v3

      - name: AWS creds configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ env.AWS_REGION }}

      - name: login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: build, tag and push image
        id: build-and-push
        run: |
          docker build -t ${{steps.ecr-login.outputs.registry}}/${{env.ECR_REPO_NAME}}:${{env.IMAGE_TAG}} .
      
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.build-and-push.outputs.image }} # or specify the image tag directly
          format: table
          exit-code: 0       # Fail the workflow if vulnerabilities are found
          severity: HIGH,CRITICAL

      - name: push image to ECR
        run: |
          docker push ${{steps.ecr-login.outputs.registry}}/${{env.ECR_REPO_NAME}}:${{env.IMAGE_TAG}}
