name: Resume CI test-Build
on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build_stage:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{github.run_number}}
    - name: Build latest
      run: docker build . --file Dockerfile --tag my-image-name
    - name: Docker Login
      run: docker login -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASSWORD}}
    - name: Tag image
      run: docker tag my-image-name:${{github.run_number}} ${{secrets.REGISTRY_USERNAME}}/my-image-name:${{github.run_number}}
    - name: Push to Docker registry 
      run: docker push ${{secrets.REGISTRY_USERNAME}}/my-image-name:${{github.run_number}}

  deploy_stage:

    runs-on: ubuntu-latest
    needs: build_stage
    steps:
    - name: SSH to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{secrets.HOST}}
        username: ${{vars.EC2_USER}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        script: |
          docker stop resume || echo ""
          docker rm resume || echo ""
          docker run -d --name resume -p 8080:5001 ${{secrets.REGISTRY_USERNAME}}/my-image-name:${{github.run_number}}